travis:
  secure:
    BINSTAR_TOKEN: tJ0RR7oZ2zuMubyn4HOsuWTAJwC9DpUK/upeekavqfekUkiRxvlugRGFA8lSIowVZUx4cUNrg/1nQgEdQ2Dbc0jkiwwEU5qiEAMX2iPDIqLJmO92T5++ucRTxMYlQNENDv4tKrRJXA65mCv2slXlMRlWhJaUUvRe6opRfU6mJKXk6qGg6+2MdM8JhMf90OIm6n3+StxmaHBmu/KhHawwHOVKrM2N1kdYxtutFTnLrIYitAf5Bn04sHoe3tUe0jmJJwogoQ0jY29YYMtc3kO3xvnxPl+lX4YDfqc7B9KSHsUFCQuJXZl+1g++3fgqhL3rOodwBoe+Qoktmqls/arw4bzzuskKzJ7cXM0xkgLHQz8PcpICiHE91Z35WM3Mt5sJt+Ce3J1XMsQtbMDrt6kN4H3WtUtMFBH/zw8qacm+rIiUXg5+IChKAhK52lVkdijFKYjyxDc86odL6l1gPbeMgUtKhotG8apotnuECLM1uBNMGlm2czErMihtsgv1qyV1F6WHkaRhVccPBcGsysT8oQ7afNGNKyIC41lS8WeSCyRsS7c456Qv9MnG9/u8kH2CUy8IFm/m/GQTfS+X+Pog4lDzRNooc7HCdwoqYbquhMJgVlYSN5aOzN3j4GqslPY68fj8JS2qVJsqboY0ToXIorRV8h/p4WG+Jl4/WPmNLKc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
