travis:
  secure:
    BINSTAR_TOKEN: Y870tr8sOGfyLedt3ALcnc23sbbqHjvQqpThoF94PFXJfErUP2CPkh9mpHXVrDvUVBzcVg/It+bW582C0EFVn+nFNxg47/4UOTT2VtpfzyXY8w0mBUX7e4zo1wwTDFx28IfV30nW23R3Oi04BsEk+wz9FXtq5yH84Fgh1h10XOAzr2YFue2Smfepyc0ldKppKJm6W19Uz862rFHIRyBzlcNDw4WobZhqV0gvvtPA8Y5QBWbfuRACsgPaxgL3Vus50QhlSgnI7ry486pWCT1X//HsSSMC3n2m+9y+UmZcBiprPnSfqNdM9lK/hoTYVm0JyRf8CLmVFcGc+TTsK9XTupXRrrQgsOQRXUjb4etYd/snUlSt4VyrtJjZZhLR9g3x1lZD1h7z7tFpkLJ0U6ysw46QD84cvbwZOLcjzpEBo1k060dC8j+Oqxo1+8uRM+dYyjVD4aYEnbO0URwm7do3+XocLMw34AYfw3n+ra1cFFaNbdusF36AEqG1stFmm2Hu5B14l9wVich+IGEYD2N6ov2F0htq+XmRyIzJkpK2e3eH7gm+oJOVXMWo7vIwl9Ewez7mPbgBIQZ/8EVDTfAvl6eFRpHx+u7jUkzeSPQFkHYRbDNkhFmN+pREf9nyj6Dp2bHaDl1pU05jPUQtWOr9e/WDqGF0ldB1NTpaaVhzenc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
